### PR TITLE
Merge pull request #1 from theanandankit/master

### PR DESCRIPTION
**Pull request by vatsal2600**
profile added

### CODE REVIEW

**Comment by theanandankit** [comment]
@ibacher thanks, i'm working on this and have some questions
https://github.com/theanandankit/openmrs-module-fhir2/blob/d66a68eac9cf71e18fa7224f508760b90609f894/api/src/main/java/org/openmrs/module/fhir2/model/FhirDurationUnitMap.java#L28-L41
Is this the required table that we are looking for ?? i've gone through the openMRS concept dictionary and didn't find "1822AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" or any as UUID, i think i'm finding the UUID in the wrong table. can you help me out ?

**Comment by theanandankit** [comment]
@ibacher thanks, i'm working on this and have some questions

https://github.com/theanandankit/openmrs-module-fhir2/blob/d66a68eac9cf71e18fa7224f508760b90609f894/api/src/main/java/org/openmrs/module/fhir2/model/FhirDurationUnitMap.java#L28-L41

**Comment by ibacher** [comment]
@theanandankit It's in the `concept` table, at least for the RefApp install, e.g., https://demo.openmrs.org/openmrs/owa/conceptdictionary/index.html#/concept/1822AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/, or, if you're using SQL locally:

```sql
select *
from concept
where uuid = '1822AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
```

**Comment by ibacher** [comment]
But that's assuming that you have setup a version of the RefApp... I'm not entirely sure that anything is populated in the concept dictionary if you're purely using the platform (the main reason I don't want to hard-code these values in the FHIR2 module is because the concept dictionary is defined for each OpenMRS instance and may not use the same set of concepts (though we're generally trying to discourage people from using completely different concept dictionaries).

**Comment by ibacher** [comment]
Btw, for your `unitOfTime` field, I think you need to have an annotation like `@Enumerated(EnumType.STRING)`, so Hibernate knows how to store the value in the database. The other thing I forgot to mention is you'll need to add the table definition to the [liquibase.xml file](https://github.com/theanandankit/openmrs-module-fhir2/blob/d66a68eac9cf71e18fa7224f508760b90609f894/api/src/main/resources/liquibase.xml). You should be able to follow the model of the custom tables we've added there (just be sure to pick a unique id).

**Comment by theanandankit** [comment]
@ibacher i think i've posted the comment in wrong repo sorry for that

**Comment by ibacher** [comment]
@theanandankit That's ok!

**Comment by theanandankit** [comment]
@ibacher thanks

**Pull request merged**
